.. Course
.. _mailing list: https://calmail.berkeley.edu/manage/list/listinfo/practical_fmri@lists.berkeley.edu
.. _course web directory: http://nipy.bic.berkeley.edu/practical_neuroimaging/

.. Version control
.. _git: http://git-scm.com
.. _git OSX installer: http://mackyle.github.io/git-osx-installer/
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _github: http://github.com

.. Editors
.. _vim: http://www.vim.org
.. _vi: http://en.wikipedia.org/wiki/Vi
.. _about vim: http://www.vim.org/about.php
.. _emacs tour: http://www.gnu.org/software/emacs/tour/
.. _vim: http://www.vim.org
.. _gvim: http://www.vim.org
.. _textmate: http://macromates.com
.. _textmate download for UC Berkeley: http://ist.berkeley.edu/software-central/textmate
.. _notepad++ : http://notepad-plus-plus.org/
.. _text wrangler: http://www.barebones.com/products/textwrangler/
.. _sublime text: http://www.sublimetext.com/
.. _gedit: http://projects.gnome.org/gedit
.. _emacs: http://www.gnu.org/software/emacs/
.. _text editor competition:
    http://www.rackspace.com/blog/text-editor-madness-bracket-vote-for-your-favorite

.. Python and common libraries
.. _python: http://www.python.org
.. _python standard library: http://docs.python.org/2/library
.. _python.org releases: http://www.python.org/download/releases
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _numpy: http://www.numpy.org
.. _scipy: http://www.scipy.org
.. _scipy reference guide: http://docs.scipy.org/doc/scipy/reference/
.. _matplotlib: http://matplotlib.org/
.. _matplotlib gallery: http://matplotlib.org/gallery
.. _cython: http://cython.org/
.. _sympy: http://sympy.org
.. _pandas: http://pandas.pydata.org/
.. _scikit-learn: http://scikit-learn.org/
.. _scikit-image: http://scikit-image.org/
.. _statsmodels: http://statsmodels.sourceforge.net/
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _pip: http://pypi.python.org/pypi/pip

.. IPython
.. _ipython: http://ipython.org/
.. _ipython notebook: http://ipython.org/ipython-doc/dev/interactive/htmlnotebook.html

.. Virtualenv and helpers
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://www.doughellmann.com/projects/virtualenvwrapper
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes

.. Pypi and packaging
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg

.. Mac development
.. _macports: http://www.macports.org
.. _github osx installation: http://help.github.com/mac-git-installation
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _macvim: https://github.com/b4winckler/macvim
.. _bdist_mpkg: http://pypi.python.org/pypi/bdist_mpkg
.. _parallels: http://www.parallels.com

.. Windows development
.. _mingw: http://www.mingw.org/wiki/Getting_Started
.. _msys: http://www.mingw.org/wiki/MSYS
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Nipy and friends
.. _nipy community: http://nipy.org
.. _nipy project: http://nipy.org/nipy
.. _nibabel: http://nipy.org/nibabel
.. _dipy: http://nipy.org/dipy
.. _nipype: http://nipy.org/nipype
.. _gitwash: http://github.com/matthew-brett/gitwash

.. Places
.. _brain imaging center: http://bic.berkeley.edu/
.. _BIC: http://bic.berkeley.edu/

.. FMRI datasets
.. _openfmri: https://openfmri.org/
.. _duncan et al data: https://openfmri.org/dataset/ds000107

.. Languages
.. _matlab: http://www.mathworks.com

.. Imaging software
.. _spm: http://www.fil.ion.ucl.ac.uk/spm
.. _eeglab: http://sccn.ucsd.edu/eeglab
.. _AFNI: http://afni.nimh.nih.gov/afni
.. _FSL: http://www.fmrib.ox.ac.uk/fsl
.. _FreeSurfer: http://surfer.nmr.mgh.harvard.edu
.. _voxbo: http://www.voxbo.org
.. _fmristat: http://www.math.mcgill.ca/keith/fmristat

.. Installation
.. _Python(X,Y): https://code.google.com/p/pythonxy/
.. _Python(X,Y) UK mirror: http://www.mirrorservice.org/sites/pythonxy.com
.. _blocked by Google code: http://nipyworld.blogspot.com/2011/07/why-you-shouldnt-use-google-code.html
.. _Enthought Python Distribution: http://www.enthought.com/products/epd.php
.. _Anaconda: https://store.continuum.io/cshop/anaconda
.. _EPD: http://www.enthought.com/products/epd.php
.. _Enthought canopy: https://www.enthought.com/products/canopy/
.. _checklist script: http://fperez.org/py4science/workshop_checklist.py
.. _NeuroDebian: http://neuro.debian.net
.. _VirtualBox: https://www.virtualbox.org/

.. Tutorials
.. _The Python tutorial: http://docs.python.org/2/tutorial/
.. _The Python 3 tutorial: http://docs.python.org/3/tutorial/
.. _Introduction to Python: http://www.introtopython.org
.. _Scipy lecture notes: http://scipy-lectures.github.io
.. _numpy array object: http://scipy-lectures.github.io/intro/numpy/array_object.html
.. _Array operations: http://scipy-lectures.github.io/intro/numpy/operations.html

.. People
.. _Matthew : http://matthew.dynevor.org
.. _Matthew Brett : http://matthew.dynevor.org
.. _Richard Stallman: http://en.wikipedia.org/wiki/Richard_Stallman

.. Licenses
.. _cc-by-nc-sa: http://creativecommons.org/licenses/by-nc-sa/4.0

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:
