.. Course
.. _mailing list: https://calmail.berkeley.edu/manage/list/listinfo/practical_fmri@lists.berkeley.edu
.. _course web directory: http://nipy.bic.berkeley.edu/practical_neuroimaging/

.. Version control
.. _git: http://git-scm.com
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _github: http://github.com

.. Editors
.. _vim: http://www.vim.org
.. _textmate: http://macromates.com
.. _textmate download for UC Berkeley: http://ist.berkeley.edu/software-central/textmate
.. _notepad++ : http://notepad-plus-plus.org/

.. Python and common libraries
.. _python: http://www.python.org
.. _python.org releases: http://www.python.org/download/releases
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _numpy: http://sourceforge.net/projects/numpy/files
.. _scipy: http://sourceforge.net/projects/scipy/files
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb

.. IPython
.. _ipython: http://ipython.org/
.. _ipython notebook: http://ipython.org/ipython-doc/dev/interactive/htmlnotebook.html

.. Virtualenv and helpers
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://www.doughellmann.com/projects/virtualenvwrapper
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes

.. Pypi and packaging
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg

.. Mac development
.. _macports: http://www.macports.org
.. _github osx installation: http://help.github.com/mac-git-installation
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _macvim: https://github.com/b4winckler/macvim
.. _bdist_mpkg: http://pypi.python.org/pypi/bdist_mpkg
.. _parallels: http://www.parallels.com

.. Windows development
.. _mingw: http://www.mingw.org/wiki/Getting_Started
.. _msys: http://www.mingw.org/wiki/MSYS
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Nipy and friends
.. _nipy: http://nipy.org
.. _gitwash: http://github.com/matthew-brett/gitwash

.. Places
.. _brain imaging center: http://bic.berkeley.edu/
.. _BIC: http://bic.berkeley.edu/

.. FMRI datasets
.. _openfmri: https://openfmri.org/
.. _duncan et al data: https://openfmri.org/dataset/ds000107

.. Languages
.. _matlab: http://www.mathworks.com

.. Imaging software
.. _spm: http://www.fil.ion.ucl.ac.uk/spm
.. _eeglab: http://sccn.ucsd.edu/eeglab
.. _AFNI: http://afni.nimh.nih.gov/afni
.. _FSL: http://www.fmrib.ox.ac.uk/fsl
.. _FreeSurfer: http://surfer.nmr.mgh.harvard.edu
.. _voxbo: http://www.voxbo.org
.. _fmristat: http://www.math.mcgill.ca/keith/fmristat

.. Installation
.. _Enthought Python Distribution: http://www.enthought.com/products/epd.php
.. _EPD: http://www.enthought.com/products/epd.php
.. _checklist script: http://fperez.org/py4science/workshop_checklist.py
.. _NeuroDebian: http://neuro.debian.net

.. Tutorials
.. _The Python tutorial: http://docs.python.org/2/tutorial/

.. Substitutions
.. |emdash| unicode:: U+02014
